name: Feature Request
description: Suggest an idea or enhancement for this project
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out this form as completely as possible.
  
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when...
    validations:
      required: false
  
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: I would like to be able to...
    validations:
      required: true
  
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: I've also considered...
    validations:
      required: false
  
  - type: dropdown
    id: api-coverage
    attributes:
      label: Is this related to Invoice Ninja API coverage?
      description: Does this feature request involve adding support for an existing Invoice Ninja API endpoint?
      options:
        - "Yes - New API endpoint support"
        - "No - SDK improvement"
        - "Not sure"
    validations:
      required: true
  
  - type: textarea
    id: api-docs
    attributes:
      label: API Documentation
      description: If this is related to API coverage, please provide a link to the Invoice Ninja API documentation
      placeholder: https://api-docs.invoicing.co/#/...
    validations:
      required: false
  
  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: Describe your use case and how this feature would help you
      placeholder: I need this feature because...
    validations:
      required: false
  
  - type: textarea
    id: example
    attributes:
      label: Code example
      description: If applicable, provide a code example of how you would like to use this feature
      render: go
      placeholder: |
        package main
        
        import "github.com/AshkanYarmoradi/go-invoice-ninja"
        
        func main() {
            // Example of how you'd like to use the feature
        }
    validations:
      required: false
  
  - type: dropdown
    id: contribution
    attributes:
      label: Are you willing to contribute?
      description: Would you be interested in contributing this feature via a pull request?
      options:
        - "Yes, I'd like to contribute"
        - "Maybe, with guidance"
        - "No, but I'd be happy to test"
        - "No"
    validations:
      required: false
  
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
